# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "00_core.ipynb",
         "say_goodbye": "00_core.ipynb",
         "say_ciao": "01_example.ipynb",
         "start_small_talk": "01_example.ipynb"}

modules = ["core.py"]

doc_url = "https://DonSalv.github.io/nbdevtest/"

git_url = "https://github.com/DonSalv/nbdevtest/tree/master/"

def custom_doc_links(name): return None
