# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['say_hello']

# Cell
def say_hello(to:str) -> str:
    """
    A quikc example of a function
    :param to: The name of the person to greet
    :return: A string with a greeting
    """
    return f"Hello {to}!"