# AUTOGENERATED! DO NOT EDIT! File to edit: 01_example.ipynb (unless otherwise specified).

__all__ = ['say_hello', 'say_goodbye', 'say_ciao', 'start_small_talk']

# Cell
def say_hello(to:str) -> str:
    """A quick example of a function

    :param to: The name of the person to greet

    :return: A string with a greeting
    """
    return f"Hello {to}!"

# Cell
def say_goodbye(to:str) -> str:
    """A second example of a quick function

    :param to: The name of the person to say bye

    :return: A string with a farewell
    """
    return f"Goodbye {to}!"

# Cell
def say_ciao(to:str) -> str:
    """A quick example of farewell function

    :param to: The name of the person to say goodbye

    :return: A string with a farewell
    """
    return f"Goodbye {to}!"

# Cell
def start_small_talk(to:str) -> str:
    """A second example of a quick function

    :param to: The name of the person to start the small talk

    :return: A string with a small talk sentence
    """
    phrases = ["Good Weather!", "Nice Try", "Maybe next time"]


    return f"{random.choice(phrases)} {to}!"