# AUTOGENERATED! DO NOT EDIT! File to edit: 02_testing.ipynb (unless otherwise specified).

__all__ = ['say_ciao_2', 'start_small_talk_2']

# Cell
def say_ciao_2(to:str) -> str:
    """A quick example of farewell function

    :param to: The name of the person to say goodbye

    :return: A string with a farewell
    """
    return f"Goodbye {to}!"

# Cell
def start_small_talk_2(to:str) -> str:
    """A second example of a quick function

    :param to: The name of the person to start the small talk

    :return: A string with a small talk sentence
    """
    phrases = ["Good Weather!", "Nice Try", "Maybe next time"]


    return f"{random.choice(phrases)} {to}!"